# Generated by Django 5.1.2 on 2024-11-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.PositiveSmallIntegerField()),
                ('fecha_pedido', models.DateField(verbose_name='Fecha de Realizado')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total del pedido')),
                ('estado_pedido', models.CharField(max_length=50, verbose_name='Estado del pedido')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Metodo de pago')),
            ],
        ),
    ]
