# Generated by Django 5.1 on 2024-11-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Producto')),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad Stock')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('id_proveedor', models.PositiveSmallIntegerField(default=0)),
                ('id_sucursal', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
