# Generated by Django 5.1.2 on 2024-11-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0002_pedido_cantidad_pedido_id_empleado_pedido_id_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
